version: 2.1
orbs:
  node: circleci/node@3.0.0
jobs:
  test:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
          cache-path: ~/project/node_modules
          override-ci-command: yarn add
      - run: 
         command: yarn jest
         name: Run YARN tests
workflows:
  node-tests:
    jobs:
      - node/test
